k_shot: 1
train:
    query_per_class_per_episode: 15
    batch_size: 1
    episode_per_epoch: 200
    epochs: 60
    lr_decay_epoch: 10
    lr_decay: 0.5
    learning_rate: 0.0005
    optim: "SGD"
model:
    query: "LS"
    encoder: "R12"
    ls:
        gamma: 30.0
test:
    batch_size: 1
