k_shot: 1
n_way: 5
model:
    encoder: "R12-pre"
    mel:
        gamma: 20.0
test:
    batch_size: 1
pre:
    pretrain_num_class: 361
    epochs: 50
    lr_decay_milestones: [10, 20, 30, 40]
    val_episode: 1000
    snapshot_epoch: 10
    snapshot_interval: 2
