k_shot: 1
train:
    query_per_class_per_episode: 8
    batch_size: 1
    episode_per_epoch: 200
    epochs: 40
    lr_decay_epoch: 10
    lr_decay: 0.5
    learning_rate: 0.0005
    optim: "SGD"
model:
    query: "MEL"
    encoder: "R12"
    forward_encoding: "Grid-3,2"
test:
    query_per_class_per_episode: 8
    batch_size: 1
